[general]
library_name = "libwebsockets"
use_julia_native_enum_type = true
use_deterministic_symbol = true
print_enum_as_integer = true
generate_isystem_symbols = true
output_ignorelist = [
    "LWS_O_RDONLY",
    "LWS_O_WRONLY",
    "LWS_O_CREAT",
    "LWS_O_TRUNC",
    "_LWS_PAD_SIZE",
    "LWS_FOP_SEEK_CUR",
    "LWS_POLLHUP",
    "LWS_POLLIN",
    "LWS_POLLOUT",
    "LWS_PRE"
    ]
export_symbol_prefixes = ["lws_", "LWS"]
prologue_file_path = "./prologue.jl"
# epilogue_file_path = "./epilogue.jl"

[codegen]
use_ccall_macro = true
wrap_variadic_function = true

[codegen.macro]
macro_mode = "basic"